# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #F6C35C")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1200, 300))
        self.frame.setStyleSheet("background-color: #CCFFE5")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(450, 30, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("color: white\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.a1 = QtWidgets.QLineEdit(self.frame)
        self.a1.setGeometry(QtCore.QRect(290, 100, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a1.setFont(font)
        self.a1.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a1.setText("")
        self.a1.setAlignment(QtCore.Qt.AlignCenter)
        self.a1.setObjectName("a1")
        self.a2 = QtWidgets.QLineEdit(self.frame)
        self.a2.setGeometry(QtCore.QRect(390, 100, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a2.setFont(font)
        self.a2.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a2.setText("")
        self.a2.setAlignment(QtCore.Qt.AlignCenter)
        self.a2.setObjectName("a2")
        self.a3 = QtWidgets.QLineEdit(self.frame)
        self.a3.setGeometry(QtCore.QRect(490, 100, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a3.setFont(font)
        self.a3.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a3.setText("")
        self.a3.setAlignment(QtCore.Qt.AlignCenter)
        self.a3.setObjectName("a3")
        self.a4 = QtWidgets.QLineEdit(self.frame)
        self.a4.setGeometry(QtCore.QRect(590, 100, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a4.setFont(font)
        self.a4.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a4.setText("")
        self.a4.setAlignment(QtCore.Qt.AlignCenter)
        self.a4.setObjectName("a4")
        self.a5 = QtWidgets.QLineEdit(self.frame)
        self.a5.setGeometry(QtCore.QRect(690, 100, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a5.setFont(font)
        self.a5.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a5.setText("")
        self.a5.setAlignment(QtCore.Qt.AlignCenter)
        self.a5.setObjectName("a5")
        self.a6 = QtWidgets.QLineEdit(self.frame)
        self.a6.setGeometry(QtCore.QRect(790, 100, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a6.setFont(font)
        self.a6.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a6.setText("")
        self.a6.setAlignment(QtCore.Qt.AlignCenter)
        self.a6.setObjectName("a6")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(350, 100, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(450, 100, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(550, 100, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(650, 100, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(750, 100, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(850, 100, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.a11 = QtWidgets.QLineEdit(self.frame)
        self.a11.setGeometry(QtCore.QRect(90, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a11.setFont(font)
        self.a11.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a11.setText("")
        self.a11.setAlignment(QtCore.Qt.AlignCenter)
        self.a11.setObjectName("a11")
        self.a12 = QtWidgets.QLineEdit(self.frame)
        self.a12.setGeometry(QtCore.QRect(190, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a12.setFont(font)
        self.a12.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a12.setText("")
        self.a12.setAlignment(QtCore.Qt.AlignCenter)
        self.a12.setObjectName("a12")
        self.a13 = QtWidgets.QLineEdit(self.frame)
        self.a13.setGeometry(QtCore.QRect(290, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a13.setFont(font)
        self.a13.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a13.setText("")
        self.a13.setAlignment(QtCore.Qt.AlignCenter)
        self.a13.setObjectName("a13")
        self.a14 = QtWidgets.QLineEdit(self.frame)
        self.a14.setGeometry(QtCore.QRect(390, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a14.setFont(font)
        self.a14.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a14.setText("")
        self.a14.setAlignment(QtCore.Qt.AlignCenter)
        self.a14.setObjectName("a14")
        self.a15 = QtWidgets.QLineEdit(self.frame)
        self.a15.setGeometry(QtCore.QRect(490, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a15.setFont(font)
        self.a15.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a15.setText("")
        self.a15.setAlignment(QtCore.Qt.AlignCenter)
        self.a15.setObjectName("a15")
        self.a16 = QtWidgets.QLineEdit(self.frame)
        self.a16.setGeometry(QtCore.QRect(590, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a16.setFont(font)
        self.a16.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a16.setText("")
        self.a16.setAlignment(QtCore.Qt.AlignCenter)
        self.a16.setObjectName("a16")
        self.a17 = QtWidgets.QLineEdit(self.frame)
        self.a17.setGeometry(QtCore.QRect(690, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a17.setFont(font)
        self.a17.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a17.setText("")
        self.a17.setAlignment(QtCore.Qt.AlignCenter)
        self.a17.setObjectName("a17")
        self.a18 = QtWidgets.QLineEdit(self.frame)
        self.a18.setGeometry(QtCore.QRect(790, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a18.setFont(font)
        self.a18.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a18.setText("")
        self.a18.setAlignment(QtCore.Qt.AlignCenter)
        self.a18.setObjectName("a18")
        self.a19 = QtWidgets.QLineEdit(self.frame)
        self.a19.setGeometry(QtCore.QRect(890, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a19.setFont(font)
        self.a19.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a19.setText("")
        self.a19.setAlignment(QtCore.Qt.AlignCenter)
        self.a19.setObjectName("a19")
        self.a20 = QtWidgets.QLineEdit(self.frame)
        self.a20.setGeometry(QtCore.QRect(990, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.a20.setFont(font)
        self.a20.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.a20.setText("")
        self.a20.setAlignment(QtCore.Qt.AlignCenter)
        self.a20.setObjectName("a20")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(150, 200, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(250, 200, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(350, 200, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(450, 200, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(550, 200, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(650, 200, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(750, 200, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(850, 200, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(950, 200, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(1050, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.buttonKVP = QtWidgets.QPushButton(self.frame)
        self.buttonKVP.setGeometry(QtCore.QRect(910, 100, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonKVP.setFont(font)
        self.buttonKVP.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: black\n"
";\n"
"\n"
"")
        self.buttonKVP.setObjectName("buttonKVP")
        self.buttonPVP = QtWidgets.QPushButton(self.frame)
        self.buttonPVP.setGeometry(QtCore.QRect(1110, 200, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonPVP.setFont(font)
        self.buttonPVP.setStyleSheet("background-color: #F6C35C;\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: black\n"
";\n"
"\n"
"")
        self.buttonPVP.setObjectName("buttonPVP")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 300, 1200, 300))
        self.frame_2.setStyleSheet("background-color: #F6C35C;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.i1_KVP = QtWidgets.QLineEdit(self.frame_2)
        self.i1_KVP.setGeometry(QtCore.QRect(130, 25, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.i1_KVP.setFont(font)
        self.i1_KVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.i1_KVP.setText("")
        self.i1_KVP.setAlignment(QtCore.Qt.AlignCenter)
        self.i1_KVP.setObjectName("i1_KVP")
        self.label_35 = QtWidgets.QLabel(self.frame_2)
        self.label_35.setGeometry(QtCore.QRect(90, 25, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.frame_2)
        self.label_36.setGeometry(QtCore.QRect(90, 125, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.i2_KVP = QtWidgets.QLineEdit(self.frame_2)
        self.i2_KVP.setGeometry(QtCore.QRect(130, 125, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.i2_KVP.setFont(font)
        self.i2_KVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.i2_KVP.setText("")
        self.i2_KVP.setAlignment(QtCore.Qt.AlignCenter)
        self.i2_KVP.setObjectName("i2_KVP")
        self.label_37 = QtWidgets.QLabel(self.frame_2)
        self.label_37.setGeometry(QtCore.QRect(90, 225, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.i3_KVP = QtWidgets.QLineEdit(self.frame_2)
        self.i3_KVP.setGeometry(QtCore.QRect(130, 225, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.i3_KVP.setFont(font)
        self.i3_KVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.i3_KVP.setText("")
        self.i3_KVP.setAlignment(QtCore.Qt.AlignCenter)
        self.i3_KVP.setObjectName("i3_KVP")
        self.label_39 = QtWidgets.QLabel(self.frame_2)
        self.label_39.setGeometry(QtCore.QRect(250, 125, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.k_KVP = QtWidgets.QLineEdit(self.frame_2)
        self.k_KVP.setGeometry(QtCore.QRect(290, 125, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.k_KVP.setFont(font)
        self.k_KVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.k_KVP.setText("")
        self.k_KVP.setAlignment(QtCore.Qt.AlignCenter)
        self.k_KVP.setObjectName("k_KVP")
        self.label_40 = QtWidgets.QLabel(self.frame_2)
        self.label_40.setGeometry(QtCore.QRect(250, 225, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.resh_KVP = QtWidgets.QLineEdit(self.frame_2)
        self.resh_KVP.setGeometry(QtCore.QRect(370, 225, 240, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resh_KVP.setFont(font)
        self.resh_KVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.resh_KVP.setText("")
        self.resh_KVP.setAlignment(QtCore.Qt.AlignCenter)
        self.resh_KVP.setObjectName("resh_KVP")
        self.centr_KVP = QtWidgets.QLineEdit(self.frame_2)
        self.centr_KVP.setGeometry(QtCore.QRect(490, 125, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.centr_KVP.setFont(font)
        self.centr_KVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.centr_KVP.setText("")
        self.centr_KVP.setAlignment(QtCore.Qt.AlignCenter)
        self.centr_KVP.setObjectName("centr_KVP")
        self.label_42 = QtWidgets.QLabel(self.frame_2)
        self.label_42.setGeometry(QtCore.QRect(830, 25, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_2)
        self.label_43.setGeometry(QtCore.QRect(250, 25, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_38 = QtWidgets.QLabel(self.frame_2)
        self.label_38.setGeometry(QtCore.QRect(670, 25, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.label_41 = QtWidgets.QLabel(self.frame_2)
        self.label_41.setGeometry(QtCore.QRect(670, 125, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_44 = QtWidgets.QLabel(self.frame_2)
        self.label_44.setGeometry(QtCore.QRect(670, 225, 40, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.i1_PVP = QtWidgets.QLineEdit(self.frame_2)
        self.i1_PVP.setGeometry(QtCore.QRect(710, 25, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.i1_PVP.setFont(font)
        self.i1_PVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.i1_PVP.setText("")
        self.i1_PVP.setAlignment(QtCore.Qt.AlignCenter)
        self.i1_PVP.setObjectName("i1_PVP")
        self.i2_PVP = QtWidgets.QLineEdit(self.frame_2)
        self.i2_PVP.setGeometry(QtCore.QRect(710, 125, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.i2_PVP.setFont(font)
        self.i2_PVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.i2_PVP.setText("")
        self.i2_PVP.setAlignment(QtCore.Qt.AlignCenter)
        self.i2_PVP.setObjectName("i2_PVP")
        self.i3_PVP = QtWidgets.QLineEdit(self.frame_2)
        self.i3_PVP.setGeometry(QtCore.QRect(710, 225, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.i3_PVP.setFont(font)
        self.i3_PVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.i3_PVP.setText("")
        self.i3_PVP.setAlignment(QtCore.Qt.AlignCenter)
        self.i3_PVP.setObjectName("i3_PVP")
        self.i4_PVP = QtWidgets.QLineEdit(self.frame_2)
        self.i4_PVP.setGeometry(QtCore.QRect(870, 25, 60, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.i4_PVP.setFont(font)
        self.i4_PVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.i4_PVP.setText("")
        self.i4_PVP.setAlignment(QtCore.Qt.AlignCenter)
        self.i4_PVP.setObjectName("i4_PVP")
        self.label_45 = QtWidgets.QLabel(self.frame_2)
        self.label_45.setGeometry(QtCore.QRect(790, 125, 80, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.k_PVP = QtWidgets.QLineEdit(self.frame_2)
        self.k_PVP.setGeometry(QtCore.QRect(870, 125, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.k_PVP.setFont(font)
        self.k_PVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.k_PVP.setText("")
        self.k_PVP.setAlignment(QtCore.Qt.AlignCenter)
        self.k_PVP.setObjectName("k_PVP")
        self.label_46 = QtWidgets.QLabel(self.frame_2)
        self.label_46.setGeometry(QtCore.QRect(830, 225, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.resh_PVP = QtWidgets.QLineEdit(self.frame_2)
        self.resh_PVP.setGeometry(QtCore.QRect(950, 225, 240, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.resh_PVP.setFont(font)
        self.resh_PVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.resh_PVP.setText("")
        self.resh_PVP.setAlignment(QtCore.Qt.AlignCenter)
        self.resh_PVP.setObjectName("resh_PVP")
        self.label_47 = QtWidgets.QLabel(self.frame_2)
        self.label_47.setGeometry(QtCore.QRect(990, 125, 80, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.centr_PVP = QtWidgets.QLineEdit(self.frame_2)
        self.centr_PVP.setGeometry(QtCore.QRect(1070, 125, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.centr_PVP.setFont(font)
        self.centr_PVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.centr_PVP.setText("")
        self.centr_PVP.setAlignment(QtCore.Qt.AlignCenter)
        self.centr_PVP.setObjectName("centr_PVP")
        self.label_50 = QtWidgets.QLabel(self.frame_2)
        self.label_50.setGeometry(QtCore.QRect(410, 125, 80, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.type_KVP = QtWidgets.QLineEdit(self.frame_2)
        self.type_KVP.setGeometry(QtCore.QRect(360, 20, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.type_KVP.setFont(font)
        self.type_KVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.type_KVP.setText("")
        self.type_KVP.setAlignment(QtCore.Qt.AlignCenter)
        self.type_KVP.setObjectName("type_KVP")
        self.label_51 = QtWidgets.QLabel(self.frame_2)
        self.label_51.setGeometry(QtCore.QRect(950, 25, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.type_PVP = QtWidgets.QLineEdit(self.frame_2)
        self.type_PVP.setGeometry(QtCore.QRect(1070, 25, 120, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.type_PVP.setFont(font)
        self.type_PVP.setStyleSheet("background-color: #CCFFE5;\n"
"\n"
"border: 2px solid white/n;\n"
"border-radius: 30;\n"
"color: white;\n"
"\n"
"")
        self.type_PVP.setText("")
        self.type_PVP.setAlignment(QtCore.Qt.AlignCenter)
        self.type_PVP.setObjectName("type_PVP")
        self.button_graf = QtWidgets.QPushButton(self.frame_2)
        self.button_graf.setGeometry(QtCore.QRect(560, 25, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setBold(True)
        font.setWeight(75)
        self.button_graf.setFont(font)
        self.button_graf.setStyleSheet("background-color: #CCFFE5")
        self.button_graf.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ads.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_graf.setIcon(icon)
        self.button_graf.setIconSize(QtCore.QSize(50, 50))
        self.button_graf.setObjectName("button_graf")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Калькулятор ПВП и КВП"))
        self.label_2.setText(_translate("MainWindow", "x²+"))
        self.label_3.setText(_translate("MainWindow", "xy+"))
        self.label_4.setText(_translate("MainWindow", "y²+"))
        self.label_5.setText(_translate("MainWindow", "x+"))
        self.label_6.setText(_translate("MainWindow", "y+"))
        self.label_7.setText(_translate("MainWindow", "C = 0"))
        self.label_8.setText(_translate("MainWindow", "x²+"))
        self.label_9.setText(_translate("MainWindow", "y²+"))
        self.label_10.setText(_translate("MainWindow", "z²+"))
        self.label_11.setText(_translate("MainWindow", "xy+"))
        self.label_12.setText(_translate("MainWindow", "xz+"))
        self.label_13.setText(_translate("MainWindow", "yz+"))
        self.label_14.setText(_translate("MainWindow", "x+"))
        self.label_15.setText(_translate("MainWindow", "y+"))
        self.label_16.setText(_translate("MainWindow", "z+"))
        self.label_17.setText(_translate("MainWindow", "C = 0"))
        self.buttonKVP.setText(_translate("MainWindow", "Go"))
        self.buttonPVP.setText(_translate("MainWindow", "Go"))
        self.label_35.setText(_translate("MainWindow", "I₁ ="))
        self.label_36.setText(_translate("MainWindow", "I₂ ="))
        self.label_37.setText(_translate("MainWindow", "I₃ ="))
        self.label_39.setText(_translate("MainWindow", "K ="))
        self.label_40.setText(_translate("MainWindow", "Канонич. ур-ие"))
        self.label_42.setText(_translate("MainWindow", "I₄  ="))
        self.label_43.setText(_translate("MainWindow", "Тип кривой:"))
        self.label_38.setText(_translate("MainWindow", "I₁ ="))
        self.label_41.setText(_translate("MainWindow", "I₂ ="))
        self.label_44.setText(_translate("MainWindow", "I₃ ="))
        self.label_45.setText(_translate("MainWindow", "K2,K3 ="))
        self.label_46.setText(_translate("MainWindow", "Канонич. ур-ие"))
        self.label_47.setText(_translate("MainWindow", "Центр:"))
        self.label_50.setText(_translate("MainWindow", "Центр:"))
        self.label_51.setText(_translate("MainWindow", "Тип поверхносити:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
